# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               TolX
tagline:             'Where are we in the universe..'
description:         'Universe that is expanding bit by bit'
url:                 https://tolx.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             1.0.0
